# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import file_pb2 as file__pb2


class ProcessingServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.calculate = channel.stream_stream(
        '/bidirectional.ProcessingServer/calculate',
        request_serializer=file__pb2.Request.SerializeToString,
        response_deserializer=file__pb2.Response.FromString,
        )


class ProcessingServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def calculate(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProcessingServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'calculate': grpc.stream_stream_rpc_method_handler(
          servicer.calculate,
          request_deserializer=file__pb2.Request.FromString,
          response_serializer=file__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'bidirectional.ProcessingServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
